version: '3.9'

services:
  web:
    build: .
    container_name: django_blog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/app/media
      - static:/app/static
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  media:
  static:
